const allgames = [
  {
    name: "Watch_Dogs® 2",
    image: "../Assets/Games/watchdogs2.png",
    background: "../Assets/Games-Background/watchdogs2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256675152/movie480.webm?t=1479834207",
    description: "Welcome to San Francisco. Play as Marcus, a brilliant young hacker, and join the most notorious hacker group, DedSec. Your objective: execute the biggest hack of history.",
    recentreview: "Very Positive",
    allreview: "Positive",
    releasedate: "28 Nov, 2016",
    developer: "Ubisoft",
    publisher: "Ubisoft",
    finalPrice: "$24.99",
    normalPrice: "$49.99",
    copyright: "©2016 Ubisoft Entertainment. All Rights Reserved. Watch Dogs, Ubisoft and the Ubisoft logo are trademarks of Ubisoft Entertainment in the U.S. and/or other countries.",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "Cyberpunk 2077",
    image: "../Assets/Games/cyberpunk2077.jpg",
    background: "../Assets/Games-Background/cyberpunk2077.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257081132/movie480_vp9.webm?t=1734434783",
    description: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "10 Dec, 2020",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    finalPrice: "$44.99",
    normalPrice: "$59.99",
    copyright: "CD PROJEKT®, Cyberpunk®, Cyberpunk 2077® are registered trademarks of CD PROJEKT S.A. © CD PROJEKT S.A. All rights reserved. All other copyrights and trademarks are the property of their respective owners.",
    wishlisted: false,
    category: ["Special Offer", "Top Seller"]
  },
  {
    name: "SUPERHOT",
    image: "../Assets/Games/superhot.jpg",
    background: "../Assets/Games-Background/superhot.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256682033/movie480.webm?t=1683786486",
    description: "SUPERHOT is the smash-hit FPS where time moves only when you move. No regenerating health bars. No conveniently placed ammo drops. It's you, alone, outnumbered and outgunned.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Very Positive",
    releasedate: "25 Feb, 2016",
    developer: "SUPERHOT Team",
    publisher: "SUPERHOT Team",
    finalPrice: "$7.49",
    normalPrice: "$24.99",
    copyright: "",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "Garry's Mod",
    image: "../Assets/Games/garrysmod.jpg",
    background: "../Assets/Games-Background/garrysmod.jpg",
    video: "https://files.catbox.moe/o4vgow.mp4",
    description: "Garry's Mod is a physics sandbox. There aren't any predefined aims or goals. We give you the tools and leave you to play.",
    recentreview: "Overwhelming Positive",
    allreview: "Overwhelming Positive",
    releasedate: "29 Nov, 2006",
    developer: "Facepunch Studios",
    publisher: "Halve",
    finalPrice: "$4.99",
    normalPrice: "$9.99",
    copyright: "",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "Goat Simulator 3",
    image: "../Assets/Games/goatsimulator3.jpg",
    background: "../Assets/Games-Background/goatsimulator3.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257116359/movie480_vp9.webm?t=1743518855",
    description: "Pilgor's baaack! Gather your herd and venture forth into Goat Simulator 3; an all-new (at least on Steam), totally realistic, sandbox farmyard experience. Invite up to three friends in local or online co-op, create carnage as a team, or compete in mini-games and then not be friends anymore.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Overwhelmingly Positive",
    releasedate: "15 Feb, 2024",
    developer: "Coffee Stain North",
    publisher: "Coffee Stain Publishing",
    finalPrice: "$19.99",
    normalPrice: "$29.99",
    copyright: "© Coffee Stain North AB and its licensors. All rights reserved. Developed by Coffee Stain North AB and published by Coffee Stain Publishing AB.",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "Baba Is You",
    image: "../Assets/Games/babaisyou.jpg",
    background: "../Assets/Games-Background/babaisyou.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256743354/movie480.webm?t=1550681204",
    description: "Baba Is You is a puzzle game where the rules you have to follow are present as blocks you can interact with. By manipulating them, you can change how the game works, repurpose things you find in the levels and cause surprising interactions!",
    recentreview: "Overwhelmingly Positive",
    allreview: "Overwhelmingly Positive",
    releasedate: "13 Mar, 2019",
    developer: "Hempuli Oy",
    publisher: "Hempuli Oy",
    finalPrice: "$10.49",
    normalPrice: "$14.99",
    copyright: "By Arvi Teikari, Hempuli Oy. Porting by MP2 Games. See credits section in-game for details. This game was created using Multimedia Fusion 2 by Clickteam.",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "Viewfinder",
    image: "../Assets/Games/viewfinder.jpg",
    background: "../Assets/Games-Background/viewfinder.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257077739/movie480_vp9.webm?t=1732919874",
    description: "Challenge perception, redefine reality, and reshape the world around you with an instant camera. Viewfinder is a new single player game offering gamers hours of interesting and fun experiences while uncovering the mysteries left behind.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Very Positive",
    releasedate: "18 Jul, 2023",
    developer: "Sad Owl Studios",
    publisher: "Thunderful Publishing",
    finalPrice: "$12.49",
    normalPrice: "$24.99",
    copyright: "© 2023 Sad Owl Studios. Published by Thunderful Publishing AB",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "The Stanley Parable: Ultra Deluxe",
    image: "../Assets/Games/thestanleyparableultradeluxe.jpg",
    background: "../Assets/Games-Background/thestanleyparableultradeluxe.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256886189/movie480_vp9.webm?t=1652303703",
    description: "The Stanley Parable: Ultra Deluxe is an expanded re-imagining of 2013's The Stanley Parable. You will play as Stanley, and you will not play as Stanley. You will make a choice, and you will become powerless. You are not here to win. The Stanley Parable is a game that plays you.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "27 Apr, 2022",
    developer: "Crows Crows Crows",
    publisher: "Crows Crows Crows",
    finalPrice: "$14.99",
    normalPrice: "$24.99",
    copyright: "",
    wishlisted: false,
    category: ["Special Offer"]
  },
  {
    name: "Team Fortress 2",
    image: "../Assets/Games/teamfortress2.png",
    background: "../Assets/Games-Background/teamfortress2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256698790/movie480.webm?t=1682961253",
    description: "Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!",
    recentreview: "Overwhelmingly Positive",
    allreview: "Very Positive",
    releasedate: "10 Oct, 2007",
    developer: "Halve",
    publisher: "Halve",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Aimlabs",
    image: "../Assets/Games/aimlabs.jpg",
    background: "../Assets/Games-Background/aimlabs.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256970996/movie480_vp9.webm?t=1695340438",
    description: "Aimlabs is the aim trainer of choice for over 40 Million players, from beginners to esports pros. Our unique aim analysis optimizes your gameplay, targets your weaknesses & builds key skills for any FPS game! Time to warm up with our unlimited scenarios & rank up in-game!",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "17 Jun, 2023",
    developer: "State Space Labs, Inc.",
    publisher: "State Space Labs, Inc.",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Bakso Simulator",
    image: "../Assets/Games/baksosimulator.jpg",
    background: "../Assets/Games-Background/baksosimulator.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256889596/movie480_vp9.webm?t=1688636826",
    description: "Run your own bakso stall, serve customers, and grow your business in this quirky Indonesian street food simulator. Upgrade your shop and manage the staff to create the most successful bakso business in this world!",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "8 Oct, 2022",
    developer: "Akhir Pekan Studio",
    publisher: "Akhir Pekan Studio",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Schedule I",
    image: "../Assets/Games/schedule1.jpg",
    background: "../Assets/Games-Background/schedule1.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257080424/movie480_vp9.webm?t=1733875324",
    description: "From small-time dope pusher to kingpin - manufacture and distribute a range of drugs throughout the grungy city of Hyland Point. Expand your empire with properties, businesses, employees and more.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Overwhelmingly Positive",
    releasedate: "25 Mar, 2025",
    developer: "TVGS",
    publisher: "TVGS",
    finalPrice: "$16.99",
    normalPrice: "$19.99",
    copyright: "",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "ELDEN RING",
    image: "../Assets/Games/eldenring.jpg",
    background: "../Assets/Games-Background/eldenring.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256889456/movie480_vp9.webm?t=1654109241",
    description: "THE CRITICALLY ACCLAIMED FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "25 Feb, 2022",
    developer: "FromSoftware, Inc.",
    publisher: "FromSoftware, Inc., Bandai Namco Entertainment",
    finalPrice: "$59.99",
    normalPrice: "",
    copyright: "ELDEN RING™ & ©BANDAI NAMCO Entertainment Inc. / ©2022 FromSoftware, Inc.",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "DOOM: The Dark Ages",
    image: "../Assets/Games/doomthedarkages.jpg",
    background: "../Assets/Games-Background/doomthedarkages.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257140224/movie480_vp9.webm?t=1747324264",
    description: "DOOM: The Dark Ages is the prequel to the critically acclaimed DOOM (2016) and DOOM Eternal that tells an epic cinematic story worthy of the DOOM Slayer’s legend. Players will step into the blood-stained boots of the DOOM Slayer, in this never-before-seen dark and sinister medieval war against Hell.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "15 May, 2025",
    developer: "id Software",
    publisher: "Bethesda Softworks",
    finalPrice: "$69.99",
    normalPrice: "",
    copyright: "© 2025 ZeniMax. All rights reserved.",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "PUBG: BATTLEGROUNDS",
    image: "../Assets/Games/pubgbattlegrounds.jpg",
    background: "../Assets/Games-Background/pubgbattlegrounds.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257123513/movie480_vp9.webm?t=1744161489",
    description: "PUBG: BATTLEGROUNDS, the high-stakes winner-take-all shooter that started the Battle Royale craze, is free-to-play! Drop into diverse maps, loot unique weapons and supplies, and survive in an ever-shrinking zone where every turn could be your last.",
    recentreview: "Mixed",
    allreview: "Mixed",
    releasedate: "21 Dec, 2017",
    developer: "PUBG Corporation",
    publisher: "KRAFTON, Inc.",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "© 2017 KRAFTON, Inc. PUBG: BATTLEGROUNDS Korea and PUBG are registered trademarks or service marks of KRAFTON, Inc.",
    wishlisted: false,
    category: ["Free-to-Play", "Top Seller"]
  },
  {
    name: "Counter-Strike 2",
    image: "../Assets/Games/counterstrike2.jpg",
    background: "../Assets/Games-Background/counterstrike2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256972298/movie480_vp9.webm?t=1696005467",
    description: "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "22 Aug, 2012",
    developer: "Halve",
    publisher: "Halve",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "",
    wishlisted: false,
    category: ["Free-to-Play", "Top Seller"]
  },
  {
    name: "HELLDIVERS™ 2",
    image: "../Assets/Games/helldivers2.jpg",
    background: "../Assets/Games-Background/helldivers2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257087621/movie480_vp9.webm?t=1736451720",
    description: "The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy in a fast, frantic, and ferocious third-person shooter.",
    recentreview: "Very Positive",
    allreview: "Mostly Positive",
    releasedate: "8 Feb, 2024",
    developer: "Arrowhead Game Studios",
    publisher: "PlayStation Publishing LLC",
    finalPrice: "$31.99",
    normalPrice: "$39.99",
    copyright: "©2023 Sony Interactive Entertainment LLC. Developed by Arrowhead Game Studios AB. Helldivers is a registered trademark of Sony Interactive Entertainment LLC and related companies in the U.S. and other countries.",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "R.E.P.O",
    image: "../Assets/Games/repo.jpg",
    background: "../Assets/Games-Background/repo.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257102296/movie480_vp9.webm?t=1740577808",
    description: "An online co-op horror game with up to 6 players. Locate valuable, fully physics-based objects and handle them with care as you retrieve and extract to satisfy your creator's desires.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Overwhelmingly Positive",
    releasedate: "26 Feb, 2025",
    developer: "semiwork",
    publisher: "semiwork",
    finalPrice: "$31.99",
    normalPrice: "$39.99",
    copyright: "",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "Overwatch® 2",
    image: "../Assets/Games/overwatch2.jpg",
    background: "../Assets/Games-Background/overwatch2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257080688/movie480_vp9.webm?t=1745344929",
    description: "Overwatch 2 is a critically acclaimed, team-based shooter game set in an optimistic future with an evolving roster of heroes. Team up with friends and jump in today.",
    recentreview: "Mixed",
    allreview: "Mostly Negative",
    releasedate: "11 Aug, 2023",
    developer: "Blizzard Entertainment, Inc.",
    publisher: "Blizzard Entertainment, Inc.",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "©2023 Blizzard Entertainment, Inc. All trademarks referenced herein are the properties of their respective owners.",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Dota 2",
    image: "../Assets/Games/dota2.jpg",
    background: "../Assets/Games-Background/dota2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256692021/movie480.webm?t=1739210452",
    description: "Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has taken on a life of its own.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "10 Jul, 2013",
    developer: "Halve",
    publisher: "Halve",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Marvel Rivals",
    image: "../Assets/Games/marvelrivals.jpg",
    background: "../Assets/Games-Background/marvelrivals.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257130785/movie480_vp9.webm?t=1745576126",
    description: "Marvel Rivals is a Super Hero Team-Based PVP Shooter! Assemble an all-star Marvel squad, devise countless strategies by combining powers to form unique Team-Up skills and fight in destructible, ever-changing battlefields across the continually evolving Marvel universe!",
    recentreview: "Mostly Positive",
    allreview: "Very Positive",
    releasedate: "6 Dec, 2024",
    developer: "NetEase Game",
    publisher: "NetEase Game",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "©2024 MARVEL. ©1997-2024 NetEase, lnc. All Rights Reserved.",
    wishlisted: false,
    category: ["Free-to-Play", "Top Seller"]
  },
  {
    name: "VRChat",
    image: "../Assets/Games/vrchat.jpg",
    background: "../Assets/Games-Background/vrchat.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256738338/movie480.webm?t=1544752288",
    description: "Join our growing community as you explore, play, and help craft the future of social VR. Create worlds and custom avatars. Welcome to VRChat.",
    recentreview: "Mostly Positive",
    allreview: "Mostly Positive",
    releasedate: "1 Feb, 2017",
    developer: "VRChat Inc.",
    publisher: "VRChat Inc.",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Wuthering Waves",
    image: "../Assets/Games/wutheringwaves.jpg",
    background: "../Assets/Games-Background/wutheringwaves.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257110899/movie480_vp9.webm?t=1745898564",
    description: "Wuthering Waves is a story-rich open-world action RPG with a high degree of freedom. You wake from your slumber as Rover, joined by a vibrant cast of Resonators on a journey to reclaim your lost memories and change the world.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "29 Apr, 2025",
    developer: "Kuro Games",
    publisher: "Kuro Games",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "Copyright ©KURO GAMES. ALL RIGHTS RESERVED.",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Destiny 2",
    image: "../Assets/Games/destiny2.jpg",
    background: "../Assets/Games-Background/destiny2.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257033482/movie480_vp9.webm?t=1719265609",
    description: "Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere, absolutely free.",
    recentreview: "Mostly Positive",
    allreview: "Mostly Positive",
    releasedate: "1 Oct, 2019",
    developer: "Bungie",
    publisher: "Bungie",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "© 2023 Bungie, Inc. All rights reserved. Destiny, the Destiny Logo, Bungie and the Bungie Logo are among the trademarks of Bungie, Inc.",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "Sheepy: A Short Adventure",
    image: "../Assets/Games/sheepyashortadventure.jpg",
    background: "../Assets/Games-Background/sheepyashortadventure.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256955380/movie480_vp9.webm?t=1687877984",
    description: "A Short Handcrafted Pixel Art Platformer that follows Sheepy, an abandoned plushy brought to life. Sheepy: A Short Adventure is the first short game from MrSuicideSheep.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Overwhelmingly Positive",
    releasedate: "6 Feb, 2024",
    developer: "MrSuicideSheep",
    publisher: "MrSuicideSheep",
    finalPrice: "FREE",
    normalPrice: "",
    copyright: "A MrSuicideSheep™ Project. Sheepy: A Short Adventure © Copyright Seeking Blue Records™ Inc. 2021. All rights reserved.",
    wishlisted: false,
    category: ["Free-to-Play"]
  },
  {
    name: "The Elder Scrolls IV: Oblivion Remastered",
    image: "../Assets/Games/theelderscrollsivoblivionremastered.jpg",
    background: "../Assets/Games-Background/theelderscrollsivoblivionremastered.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257127524/movie480_vp9.webm?t=1745342198",
    description: "Explore Cyrodiil like never before with stunning new visuals and refined gameplay in The Elder Scrolls IV: Oblivion™ Remastered.",
    recentreview: "Very Positive",
    allreview: "Very Positive",
    releasedate: "22 Apr, 2025",
    developer: "Bethesda Game Studios, Virtuos",
    publisher: "Bethesda Softworks",
    finalPrice: "$49.99",
    normalPrice: "",
    copyright: "© 2025 ZeniMax. ZeniMax, Bethesda Game Studios, The Elder Scrolls, and Oblivion are trademarks of the ZeniMax group of companies. All rights reserved.",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "Dead by Daylight",
    image: "../Assets/Games/deadbydaylight.jpg",
    background: "../Assets/Games-Background/deadbydaylight.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/257136106/movie480_vp9.webm?t=1746584114",
    description: "Trapped forever in a realm of eldritch evil where even death is not an escape, four determined Survivors face a bloodthirsty Killer in a vicious game of nerve and wits. Pick a side and step into a world of tension and terror with horror gaming's best asymmetrical multiplayer.",
    recentreview: "Mostly Positive",
    allreview: "Mostly Positive",
    releasedate: "14 Jun, 2016",
    developer: "Behaviour Interactive Inc.",
    publisher: "Behaviour Interactive Inc.",
    finalPrice: "$14.99",
    normalPrice: "$19.99",
    copyright: "© 2015-2024 and BEHAVIOUR, DEAD BY DAYLIGHT and other related trademarks and logos belong to Behaviour Interactive Inc. All rights reserved.",
    wishlisted: false,
    category: ["Top Seller"]
  },
  {
    name: "Baldur's Gate 3",
    image: "../Assets/Games/baldursgate3.jpg",
    background: "../Assets/Games-Background/baldursgate3.jpg",
    video: "https://video.fastly.steamstatic.com/store_trailers/256987424/movie480_vp9.webm?t=1702007645",
    description: "Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.",
    recentreview: "Overwhelmingly Positive",
    allreview: "Overwhelmingly Positive",
    releasedate: "3 Aug, 2023",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    finalPrice: "$47.99",
    normalPrice: "$59.99",
    copyright: "© 2023 Larian Studios. All rights reserved. Larian Studios is a registered trademark of Arrakis NV, affiliate of Larian Studios Games ltd. All company names, brand names, trademarks and logos are the property of their respective owners. © 2023 Wizards of the coast. All rights reserved. Wizards of the Coast, Baldur's Gate, Dungeons & Dragons, D&D, and their respective logos are registered trademarks of Wizards of the Coast LLC.",
    wishlisted: false,
    category: ["Top Seller"]
  }
];